### PR TITLE
Add an index on `logged_in_user_id` for subscriptions

### PR DESCRIPTION
**Pull request by jayzes**
This is unindexed currently, but accounting for a lot of our production
query time now.

### CODE REVIEW

**Comment by jayzes** [comment]
screen shot 2017-01-13 at 4 26 38 pm

Looks like it made the expected impact on the processing time.

**Comment by steam** [comment]
Look at all those milliseconds you found! A true detective. 👍

**Comment by jayzes** [comment]
🔎

**Comment by alanpeabody** [comment]
Nice!

**Pull request merged**
