### PR TITLE
Handle push failures in async thread.

### PR DESCRIPTION
**Pull request by alanpeabody**
https://www.pivotaltracker.com/story/show/144486883

### CODE REVIEW

**Comment by alanpeabody** [comment]
@jayzes super simple suckerpunch implementation.

**Comment by Justin-Holmes** [comment]
Think we should update Nokogiri to fix the Hakiri warning?

**Comment by alanpeabody** [comment]
@Justin-Holmes probably, but lets add a ticket and do it in it's own PR. It isn't a direct dependency, so it might take updating some other gems etc.

**Comment by alanpeabody** [comment]
@jayzes I didn't see your comments the other day (maybe because you were flagged? - I saw Justins). I started to look at the nokogiri thing, but stopped when I realized it would require updating a handful of dependencies and created this ticket:

https://www.pivotaltracker.com/story/show/145615515

**Pull request merged**
